name: Add Workflows (with Filter)

on:
  create:
    tags:
      - '*'   # Trigger on the creation of any tag
  workflow_dispatch: # Add this line for manual triggering

jobs:
  copy-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy workflows
        run: |
          cp -r .github/workflow-templates/.github/workflows ${{ github.event.repository.full_name }}/.github/workflows
